### ISSUE TITLE
Does this plugin only get used when navigate is called directly?

### ISSUE THREAD

**Issue by georgephillips** [veracross/backbone-beforepopstate#2]
I have updated all my code to use backbone 1.0 and have installed the plugin but the _pushHistory object stays permanently empty. The navigate override never gets run when I click a link.

**Comment by wbond** [comment]
Yeah, with backbone you have to call `.navigate(url)` when a user clicks a link. This is one of the big missing pieces of the backbone docs in regards to pushState. I use a global link handler that looks for local links and only handles those. Basically, it looks for URLs not starting with `http://` or `https://`.
